
policy: "TaskFormer-L"
algo: "TaskFormer"

env:
  dataset: "Pakistan"
  flag: "Tuple30K"
  refresh_rate: 0.005

training:
  num_epochs: 20
  batch_size: 256
  lr: 0.002
  gamma: 0.2
  epsilon: 0.1
  epsilon_decay: 0.96
  lambda: [1000, 1, 0.0]

model:
  d_model: 128
  n_layers: 16
  n_heads: 8
  mlp_ratio: 4
  dropout: 0.2  
  mode: "task" # "mixed", node, task

    